name: LeetCode Daily Sync

on:
  schedule:
    - cron: '0 1 * * *'  # runs daily at 1 AM UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: LeetCode Scraper
        uses: KshitijBarnwal/Leetcode-Questions-Scraper@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: ntAsNHb1tM
